# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirQualityMonitoring' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream', '~> 4.0.0'
  pod 'CorePlot', '~> 2.3'

  # Pods for AirQualityMonitoring

  target 'AirQualityMonitoringTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AirQualityMonitoringUITests' do
    # Pods for testing
  end

end
